require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const whatsAppService = require('./src/utils/WhatsAppService');

async function testVisitorFeature() {
    console.log('\n==================================================');
    console.log('       📋 PEOPLE-DESK VISITOR FEATURE TEST        ');
    console.log('==================================================\n');

    // 1. Check DB Connection & Table Existence
    try {
        console.log('🔍 Checking Database Connection & VisitorRecord table...');
        const count = await prisma.visitorRecord.count();
        console.log(`✅ Database connection successful! Total Visitor Records in DB: ${count}`);
    } catch (err) {
        console.error('❌ Database error: Could not query VisitorRecord table.');
        console.error('   Message:', err.message);
        console.log('👉 Make sure you ran node scripts/safe_update.js on your VPS.\n');
        process.exit(1);
    }

    // 2. Fetch Sample Users for CRE, FA, LA, BH
    console.log('\n🔍 Checking Staff Accounts in Database...');
    const creUser = await prisma.user.findFirst({ where: { status: 'ACTIVE' } });
    const faUser = await prisma.user.findFirst({ where: { status: 'ACTIVE', designation: { contains: 'FA', mode: 'insensitive' } } }) || creUser;
    const laUser = await prisma.user.findFirst({ where: { status: 'ACTIVE', designation: { contains: 'LA', mode: 'insensitive' } } }) || creUser;
    const bhUser = await prisma.user.findFirst({ where: { status: 'ACTIVE', OR: [{ role: 'BUSINESS_HEAD' }, { designation: { contains: 'BH', mode: 'insensitive' } }] } }) || creUser;

    console.log(` • CRE Account : ${creUser ? `${creUser.name} (ID: ${creUser.id})` : 'None found'}`);
    console.log(` • FA Account  : ${faUser ? `${faUser.name} (ID: ${faUser.id})` : 'None found'}`);
    console.log(` • LA Account  : ${laUser ? `${laUser.name} (ID: ${laUser.id})` : 'None found'}`);
    console.log(` • BH Account  : ${bhUser ? `${bhUser.name} (ID: ${bhUser.id})` : 'None found'}`);

    if (!creUser) {
        console.error('❌ No active users found in database to link visitor record.');
        process.exit(1);
    }

    // 3. Create a Test Visitor Record
    console.log('\n📝 Inserting Test Visitor Record into Database...');
    let testRecord;
    try {
        testRecord = await prisma.visitorRecord.create({
            data: {
                clientName: 'Test Client - ' + new Date().toLocaleTimeString(),
                phoneNumber: '919092705679',
                reasonOfVisit: 'Design discussion - 1st',
                showroom: 'MTRS',
                dateOfVisit: new Date(),
                timeOfEntry: '10:30',
                creId: creUser.id,
                faId: faUser ? faUser.id : null,
                laId: laUser ? laUser.id : null,
                bhId: bhUser ? bhUser.id : null,
                notes: 'Automated test entry generated by test_visitor_feature.js'
            },
            include: {
                cre: true,
                fa: true,
                la: true,
                bh: true
            }
        });
        console.log(`✅ Test Visitor Record created successfully! Record ID: ${testRecord.id}`);
        console.log(`   Client: ${testRecord.clientName} | Phone: ${testRecord.phoneNumber} | Showroom: ${testRecord.showroom}`);
    } catch (createErr) {
        console.error('❌ Failed to insert VisitorRecord:', createErr.message);
        process.exit(1);
    }

    // 4. Test WhatsApp Notification Dispatch
    console.log('\n📲 Testing WhatsApp Notification Dispatch...');
    const testRecipientPhone = process.env.WHATSAPP_NOTIFICATION_NUMBER || '919092705679';
    console.log(`   Target Notification Phone: ${testRecipientPhone}`);

    const details = {
        clientName: testRecord.clientName,
        phoneNumber: testRecord.phoneNumber,
        reasonOfVisit: testRecord.reasonOfVisit,
        showroom: testRecord.showroom,
        dateOfVisit: testRecord.dateOfVisit,
        timeOfEntry: testRecord.timeOfEntry,
        creName: testRecord.cre?.name || 'Test CRE',
        faName: testRecord.fa?.name || 'Test FA',
        laName: testRecord.la?.name || 'Test LA',
        bhName: testRecord.bh?.name || 'Test BH'
    };

    try {
        const waResult = await whatsAppService.sendVisitorRecordNotification(testRecipientPhone, details);
        if (waResult.success) {
            console.log('✅ SUCCESS: WhatsApp notification dispatched successfully!');
            console.log('   Response Data:', JSON.stringify(waResult.data || waResult));

            // Update record status in DB
            await prisma.visitorRecord.update({
                where: { id: testRecord.id },
                data: {
                    whatsappSent: true,
                    whatsappLog: JSON.stringify([waResult])
                }
            });
            console.log('✅ Updated record whatsappSent = true in Database.');
        } else {
            console.warn('⚠️ WARNING: WhatsApp dispatch returned false / missing credentials.');
            console.warn('   Reason:', waResult.error);
        }
    } catch (waErr) {
        console.error('❌ Error sending WhatsApp notification:', waErr.message);
    }

    console.log('\n==================================================');
    console.log('🎉 VISITOR RECORD FEATURE VERIFICATION COMPLETE!');
    console.log('==================================================\n');
}

testVisitorFeature()
    .catch((e) => console.error(e))
    .finally(() => prisma.$disconnect());
