const cron = require("node-cron");
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const { sendEmail } = require("../utils/emailService");
const {
    checkAndNotifyExcessiveRequests
} = require("../controllers/requestController");

const initWeeklyExcessiveAbsenceCron = () => {
    // Schedule the cron job to run every 2 minutes for testing purposes
    // cron.schedule("*/1 * * * *", async () => {
    // Runs every Sunday at 11:30 PM IST
    cron.schedule(
        "30 23 * * 0",
        async () => {

            console.log("Running Weekly Excessive Absence Report...");

            try {

                const today = new Date();

                // Get active employees
                const users = await prisma.user.findMany({
                    where: {
                        status: "ACTIVE",
                        role: "EMPLOYEE"
                    },
                    select: {
                        id: true
                    }
                });

                // Check excessive requests for all employees
                const report = (
                    await Promise.all(
                        users.map(user =>
                            checkAndNotifyExcessiveRequests(
                                user.id,
                                today
                            )
                        )
                    )
                ).filter(Boolean);

                const recipients = [
                    process.env.EMAIL_FROM,
                    'elakkiya.sakthivelu3089@gmail.com',
                    ...new Set(
                        report
                            .map(emp => emp.bhEmail)
                            .filter(Boolean)
                    )
                ].filter(Boolean);

                // ----------------------------------------
                // Calculate Reporting Week (Monday-Sunday)
                // ----------------------------------------
                const weekStart = new Date(today);
                const day = weekStart.getDay();
                const diff = day === 0 ? 6 : day - 1;

                weekStart.setDate(weekStart.getDate() - diff);

                const weekEnd = new Date(weekStart);
                weekEnd.setDate(weekStart.getDate() + 6);

                const reportingWeek =
                    `${weekStart.toLocaleDateString("en-GB")} - ${weekEnd.toLocaleDateString("en-GB")}`;

                // ----------------------------------------
                // No excessive requests found
                // ----------------------------------------
                if (report.length === 0) {

                    console.log("No excessive requests found.");

                    const html = `
                    <div style="font-family:Arial;padding:20px">

                        <h2 style="color:#2e7d32">
                            Weekly Excessive Absence Report
                        </h2>

                        <p>
                            <strong>Reporting Week:</strong>
                            ${reportingWeek}
                        </p>

                        <p style="font-size:16px;color:#2e7d32;">
                            ✅ There were no excessive leave requests or permission requests reported this week.
                        </p>

                        <br>

                        <p>
                            This is an automated weekly report generated by
                            <strong>PeopleDesk</strong>.
                        </p>

                    </div>
                    `;

                    await sendEmail({
                        to: recipients.join(","),


                        subject: "Weekly Excessive Absence Report - No Excessive Requests",
                        html
                    });

                    console.log("Weekly summary email sent successfully.");

                    return;
                }

                // ----------------------------------------
                // Attendance Cycle
                // ----------------------------------------
                const cycleStart = new Date(report[0].cycleStart);
                const cycleEnd = new Date(report[0].cycleEnd);

                // Restrict reporting week within attendance cycle
                if (weekStart < cycleStart) {
                    weekStart.setTime(cycleStart.getTime());
                }

                if (weekEnd > cycleEnd) {
                    weekEnd.setTime(cycleEnd.getTime());
                }

                const WEEK_IN_MS =
                    7 * 24 * 60 * 60 * 1000;



                const attendanceCycle =
                    `${cycleStart.toLocaleDateString("en-GB")} - ${cycleEnd.toLocaleDateString("en-GB")}`;

                // ----------------------------------------
                // Table Rows
                // ----------------------------------------
                const rows = report
                    .map((emp, index) => `
                        <tr>
                            <td>${index + 1}</td>
                            <td>${emp.name}</td>
                            <td>${emp.designation ?? "-"}</td>
                            <td>${emp.permissionCount}</td>
                            <td>${emp.leaveDays}</td>
                        </tr>
                    `)
                    .join("");

                // ----------------------------------------
                // Email Template
                // ----------------------------------------
                const html = `
                <div style="font-family:Arial;padding:20px">

                    <h2 style="color:#d32f2f">
                        Weekly Excessive Absence Report
                    </h2>

                    <p>
                        <strong>Attendance Cycle:</strong>
                        ${attendanceCycle}
                    </p>

                    <p>
                        <strong>Reporting Week:</strong>
                        ${reportingWeek}
                    </p>


                    <table
                        border="1"
                        cellspacing="0"
                        cellpadding="8"
                        style="border-collapse:collapse;width:100%;text-align:left">

                        <thead style="background:#eeeeee">
                            <tr>
                                <th>S.No</th>
                                <th>Name</th>
                                <th>Designation</th>
                                <th>Permissions</th>
                                <th>Leave Days</th>
                            </tr>
                        </thead>

                        <tbody>
                            ${rows}
                        </tbody>

                    </table>

                    <br>

                    <p>
                        This is an automated weekly report generated by
                        <strong>PeopleDesk</strong>.
                    </p>

                </div>
                `;


                await sendEmail({
                    to: recipients.join(","),
                    subject: 'Weekly Excessive Absence Report',
                    html
                });

                console.log(
                    `Weekly report sent successfully to ${recipients.length} recipients.`
                );

            } catch (err) {

                console.error(
                    "Weekly Excessive Absence Cron Error:",
                    err
                );

            }

        },
        {
            timezone: "Asia/Kolkata"
        }
    );

    console.log("Weekly Excessive Absence Cron Initialized");
};

module.exports = {
    initWeeklyExcessiveAbsenceCron
};
